Added SeasonByYear() method
tboothman/imdbphp pull request #243
Opened 2021-07-10 15:37 UTC by duck7000

It returns int based on how many valid years found.
So for a tv series with 2002, 2003, 2004, 2005 it returns int 4

2021-07-13 21:53 UTC, Thomasdouscha commented
I am impatiently waiting for this code :)

2021-07-15 11:05 UTC, jreklund commented
Hi, can you give me a tv-show that does this. So I can test it out fully.

2021-07-15 13:52 UTC, duck7000 commented
sure, this one:
https://www.imdb.com/title/tt0388629/

2021-07-16 11:17 UTC, jreklund requested changes
This should be combined with the normal "seasons" function, just like we do with "episodes".

2021-07-16 11:17 UTC, jreklund commented on src/Imdb/Title.php
> +    protected $seasonByYearcount = -1;
$seasoncountByYear

2021-07-16 11:17 UTC, jreklund commented on src/Imdb/Title.php
> +                    $this->seasonByYearcount = $this->seasonByYearcount + 1; // count every valid year.
$this->seasoncountByYear++;

2021-07-16 11:17 UTC, jreklund commented on src/Imdb/Title.php
> +    /** Get the number of seasons by year or 0 if not a series (Test if something is a series first with Title::is_serial())
"Get number" should be on a new line.
```
/**
* Get
```

2021-07-16 11:57 UTC, duck7000 commented
I thought about combining this with seasons but the output will be different as it aren't seasons but years?

2021-07-16 12:17 UTC, jreklund commented
Hmm, if we consider this to be a different value "not a season" then it should not be named as such e.g. "how many years this show have been running"-name. That would be more correct I guess, as episodes are just episodes no matter when/how it aired.

2021-07-16 12:58 UTC, duck7000 commented
Correct then it wouldn't be "season"by year as it aren't seasons. Good point, i'll change the method name.

I have no clue what others think about this?
@tboothman ?

And i'm not using this method myself as i don't jet need it (my tv series are all season based so far) but that might change in the future.

2021-07-16 13:06 UTC, duck7000 commented
how about this as method name:
tvSeriesyearCount or tvSeriesEpisodesByYear

It is very hard to come up with something useful

2021-07-16 13:22 UTC, jreklund commented
@duck7000 Naming convention are the hardest part of programming lol. That's why I didn't give you an example, didn't come up with one myself.

2021-07-26 09:39 UTC, duck7000 commented
Is this ready to get a final review jet?

2021-09-30 09:45 UTC, duck7000 commented
Closing this one, No more response, I don't understand why

2022-02-16 20:27 UTC, duck7000 commented
On request from @Thomasdouscha i will reopen this pr

2022-03-28 20:14 UTC, duck7000 commented
@Thomasdouscha 
Can you test this method to make sure it all works well? Try to find some more examples to test it, i only found one.

I don't get any response from @jreklund but if you test and it works at least you can use it in your program i guess

2022-03-28 21:25 UTC, Thomasdouscha commented
Yes i can but again i need the file.

2022-03-29 10:46 UTC, duck7000 commented
Okay here it is, it is up to date with the master from imdbphp but includes this method
Method name is tvSeriesByYearCount()
[Title.tvSeriesByYearCount.zip](https://github.com/tboothman/imdbphp/files/8370560/Title.tvSeriesByYearCount.zip)

2022-03-29 19:18 UTC, Thomasdouscha commented
![image](https://user-images.githubusercontent.com/43930732/160689556-7e47f78e-2d12-497d-b900-c0a5c97086a5.png)

It works but there is one mistake i explain you :

![image](https://user-images.githubusercontent.com/43930732/160689885-0508ffdf-a550-48b0-b879-31fca5631d49.png)

as you see 999.episodes highest limit. It should be 9999 minimum. Because if the episodes are based year that means there are too much episodes. I saw even 35000 episodes.

2022-03-30 09:41 UTC, duck7000 commented
It may be that you are missing the point of this method?

It just returns the number of years if the tv series is year based. It does exactly the same as seasons() but instead count how many years that series runs
So in case of one piece it will return int 24, that is all and has nothing to do with episodes.

If you mean that there is a limit on how many episodes can be returned from episodes() method than that is a bug inside that method, not in this method.

2022-03-31 21:14 UTC, Thomasdouscha commented
No.
10 digit even is possible. varchar(10). it is up to here. Maybe not from directly your code.

2022-03-31 21:20 UTC, Thomasdouscha commented
Database ok. I will check code

2022-04-01 10:45 UTC, duck7000 commented
I still think you are missing the point of this specific method that you not seem to use in your example screenshots?

This specific method just counts the amount of years just like seasons() does for season based tv series. It can't give output like your screenshots!

Witch method did you use to make above screenshots?
And what do you mean by "It is up to yourside" I did not make method episodes() so don't blame me for something i didn't do

2022-04-01 21:21 UTC, Thomasdouscha commented
If episodes get just maximum 999 episodes, Tvseriesbyyearcount for what? As i told you tvseries which year based has too much episodes. 999 well not enough. Tomorrow i will look at again and i will add my code here. Again we can concidere it

2022-04-02 10:55 UTC, duck7000 commented
I thought that this method is what you impatiently are waiting for? Now you say "for what"

Maybe we are not on the same page and think in different directions here?

What did you expect from this method? As i explained before it only returns the number of years just like seasons() does for season based series.

I think that you use episodes() and that there in your perspective is something wrong with it, hence you mentioned episodes can't be more than 999
You have to be more specific in what you want and expect, i'm lost at this point as we clearly not talking about the same thing.

2022-04-06 08:56 UTC, Thomasdouscha commented
yes you are right. I am ill thatswy i couldnot test your code. Sorry @duck7000.

2022-10-10 10:34 UTC, duck7000 commented
@Thomasdouscha 
Is this still something to discuss about?
If not i will close it because i don't think anyone would use it

2022-10-10 11:37 UTC, Thomasdouscha commented
I will use it. Because some tv series episodes based years. Not less . What was the issue about it. If you revise it i can test again.

2022-10-10 12:50 UTC, duck7000 commented
well last i checked it does what it supposed to do, returning the number of years a tv series run.
So yes you can use it but it would be nice if this get merged as well

2022-10-10 13:01 UTC, Thomasdouscha commented
So why did not they merge it?

duck7000 ***@***.***>, 10 Eki 2022 Pzt, 15:50 tarihinde şunu
yazdı:

> well last i checked it does what it supposed to do, returning the number
> of years a tv series run.
> So yes you can use it but it would be nice if this get merged as well
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tboothman/imdbphp/pull/243#issuecomment-1273267449>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKPFI3FBUIW7XTLRM2AO3T3WCQGIJANCNFSM5AEKZMZQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-13 12:36 UTC, Thomasdouscha commented
Please let you merge it after clarify ok.

2022-10-13 14:11 UTC, duck7000 commented
Well that is not up to me, @tboothman only could merge it so we will have to wait and see.
I don't understand either why this takes so long, some PR are open for more than a year. Sure it takes time to review but not that long i guess.

Only other option is for you to fork this repo and make your own version.

I did raised a issue that I'm concerned that PR requests take a very long time here, only @jreklund responded that he has no time or interest in reviewing PR anymore, and sure that is fine and clear, but means it is only up to @tboothman to act on PR requests

2022-10-22 17:15 UTC, closed without merging